name: Build and Publish Image on version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: get package version
        id: get_version
        run: echo ::set-output name=PACK_VERISON::${GITHUB_REF/refs\/tags\//}

      - name: login to github packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build image and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/ME-64/coinbase-bidask:lastest
            ghcr.io/ME-64/coinbase-bidask:${{ steps.get_version.outputs.VERSION }}
          push: true

