name: Build and Publish Image on version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: login to github packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build image and push to GHCR
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/me-64/coinbase-bidask:lastest
            ghcr.io/me-64/coinbase-bidask:${{ steps.vars.outputs.tag }}
          push: true

